modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
issueTrackerURL = "https://github.com/pixele/pixelmon-projecte-integration/issues"

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
authors = "${mod_authors}"
description = '''${mod_description}'''
logoFile = "logo.png"

# Pixelmon dependency - required
[[dependencies.${mod_id}]]
modId = "pixelmon"
type = "required"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

# ProjectE dependency - required
[[dependencies.${mod_id}]]
modId = "projecte"
type = "required"
versionRange = "[1.0.0,)"
ordering = "AFTER"
side = "BOTH"

# NeoForge dependency
[[dependencies.${mod_id}]]
modId = "neoforge"
type = "required"
versionRange = "${neo_version_range}"
ordering = "NONE"
side = "BOTH"

# Minecraft dependency
[[dependencies.${mod_id}]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
